### ISSUE TITLE
Naming of operators

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.parquet#1]
Just a plea to name operators for the function they perform in the terms of the external system., ParquetSink will not be intuitive to HDFS users, they would probably look for a ParquetWriter given the name of the api it is calling.

**Comment by apyasic** [comment]
Dan, you're absolutely right. The question is who is going to use this toolkit: HDFS developers or Streams developers? Also, the convention was used for compliancy with what other HDFS-oriented toolkits (like streamsx.hdfs).
